### PR TITLE
Support include and exclude option from tsconfig

### PR DESCRIPTION
**Pull request by torfmaster**
# Content of the PR

This PR enables support for the `include` and `exclude` fields of the `tsconfig.conf` project configuration file.

# Details

It uses the `readDirectory` function of the `compilerHost` which is also used by the compiler itself to resolve the list of files. This function may (according to the signature) not be available but the conditions under which this might be the case are unknown. I could not reproduce situations where this is the case this is why I completely removed the old file resolution mechanism. In case this change produces errors in the wild (which I doubt) we could still do an (educated) guess in a later version.

# Testing

The obvious integration test has been included in the integration tests for the files api. However, this only demonstrates that the function is properly integated, the functionality of the `readDirectory` must be tested in the `typescript` library in my opinion. The contract is, that this function resolves the files that are compiled when running tsc with the provided `tsconfig.conf`.

### CODE REVIEW

**Comment by torfmaster** [comment]
Closes #49. If you like, you can check this change using `npm link` and your code base @danielsitnik.

**Comment by danielsitnik** [comment]
Thank you @torfmaster!
I'll find some time here to do some tests and report back.

**Comment by torfmaster** [comment]
@c-harding: Would you mind doing a review of this change. I think it makes sense in any case, even though it might not fix @danielsitnik 's error.

**Comment by torfmaster** [comment]
@c-harding whould you mind reviewing this PR? I guess you are the only person with merge permissions on this repo. Thanks!

**Review by c-harding — APPROVED** [review]

**Comment by danielsitnik** [comment]
Working like a charm, thanks so much for this release!

**Pull request merged**
